### ISSUE TITLE
Meeting saved as url not launching

### ISSUE THREAD

**Issue by tomginsberg** [tmonfre/zoom-cli#4]
`zoom save --url https://utoronto.zoom.us/j/[meeting id] --password [password] -n lab`

followed by 

`zoom lab`

Output
```
Traceback (most recent call last):
  File "cli.py", line 4, in <module>
  File "click/core.py", line 1128, in __call__
  File "click/core.py", line 1053, in main
  File "click/core.py", line 1659, in invoke
  File "click/core.py", line 1395, in invoke
  File "click/core.py", line 754, in invoke
  File "zoom_cli/__main__.py", line 19, in launch
  File "zoom_cli/commands.py", line 27, in _launch_name
KeyError: 'id'
[95612] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by tmonfre** [comment]
Hi @tomginsberg thanks for reporting. I see the issue - mistake on my part. Will try to have a fix up tomorrow for this.

**Comment by tmonfre** [comment]
@tomginsberg this has been fixed in v1.1.5 (now available). Run `brew upgrade zoom` to get the latest. You may need to re-tap the cask with `brew tap tmonfre/homebrew-tmonfre`.

Thanks again for reporting that bug. Mistake on my part.

**Comment by tomginsberg** [comment]
Thanks for the fix. I am getting a SHA256 mismatch when trying to update tho

**Comment by tmonfre** [comment]
Yeah I had the same happen to me. Delete the cached file if it prompts you, then re-tap the cask. May need to run `brew install zoom` instead of `upgrade`. I was able to download the new version after doing this.

**Comment by tomginsberg** [comment]
Great works! Looking forward to effortless zoom logins
